{
  "hash": "3cee16b8784f0a49de45b0fc2e3bde86",
  "result": {
    "engine": "knitr",
    "markdown": "# Aside: Detecting a Breakpoint {- .aside-chapter}\n\n\n::: {.cell}\n\n:::\n\n\n## Introduction\n\nMann-Kendall and Theil-Sen, from the last chapter, both assume the same shape of change: a gradual, one-directional drift that runs the whole length of the record. That's a fair assumption for a warming climate or a shrinking snowpack. It's a bad assumption for a river below a new dam, a gauge that got moved, a lake after its sewage outflow was diverted, or a monitoring program that switched instruments halfway through. None of those series drift. They sit at one level, something happens, and they sit at a new level. If you hand a step change to Mann-Kendall it will usually find something (we'll watch it do exactly that below), but the number it reports describes a drift that never happened.\n\nWhat you actually want to ask is different: is there a single moment where the series stopped being one thing and became another, and if so, when? Eyeballing a plot and squinting at the year things look different is not that answer, it's a guess dressed up as an observation. This aside builds the tool that replaces the squint: find the split point that best separates a series into a before and an after, and test whether that split is worth believing at all.\n\n## Packages\n\nThe idea here is simple enough to build from scratch, and we will, once. For anything past a single break, or for a proper test of whether a break is there at all, `strucchange` [@R-strucchange] does the work. It isn't used anywhere else in the book, so consider this its one appearance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(strucchange)\n```\n:::\n\n\n## A Series That Steps Instead of Slides\n\nPlant a series with a single clean jump in it: forty-five points at a mean of 10, then thirty-five points at a mean of 15, both with the same noise.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(21)\nn <- 80\nstep <- c(rnorm(45, mean = 10, sd = 2), rnorm(35, mean = 15, sd = 2))\n\ntibble(t = 1:n, x = step) |>\n  ggplot(aes(t, x)) +\n  geom_line(color = sfPal[1]) +\n  geom_vline(xintercept = 45.5, linetype = \"dashed\", color = sfPal[5]) +\n  labs(x = \"Time\", y = \"Some variable\", title = \"A step, not a slope\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09xAsideBreakpoints_files/figure-html/bp-planted-1.png){width=672}\n:::\n:::\n\n\nNothing drifts here. The series is flat, jumps once, and is flat again. Run last chapter's tools on it anyway.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmann_kendall <- function(x) {\n  n <- length(x)\n  S <- 0\n  for (j in 2:n) {\n    for (i in 1:(j - 1)) {\n      S <- S + sign(x[j] - x[i])\n    }\n  }\n  ties <- table(x)\n  tie_term <- sum(ties * (ties - 1) * (2 * ties + 5))\n  varS <- (n * (n - 1) * (2 * n + 5) - tie_term) / 18\n  Z <- (S - sign(S)) / sqrt(varS)\n  tau <- S / (n * (n - 1) / 2)\n  p <- 2 * (1 - pnorm(abs(Z)))\n  tibble(S = S, varS = varS, Z = Z, tau = tau, p = p)\n}\n\ntheil_sen <- function(x, t = seq_along(x)) {\n  n <- length(x)\n  slopes <- c()\n  for (j in 2:n) {\n    for (i in 1:(j - 1)) {\n      slopes <- c(slopes, (x[j] - x[i]) / (t[j] - t[i]))\n    }\n  }\n  median(slopes)\n}\n\nmk_step <- mann_kendall(step)\nts_step <- theil_sen(step)\nc(tau = mk_step$tau, p = mk_step$p, theil_sen_per_unit = ts_step)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               tau                  p theil_sen_per_unit \n      4.373418e-01       9.603393e-09       9.030074e-02 \n```\n\n\n:::\n:::\n\n\nMann-Kendall reports $\\tau$ = 0.44 with a $p$-value of 9.6e-09. Screaming significant, as it should be, later values really do sit above earlier ones. The Theil-Sen slope of 0.09 per unit time, multiplied out over 79 points, lands close to the actual jump of 5. But look at what that slope claims: a steady climb, a little bit every year, for eighty years. That's not what happened. Nothing moved for forty-five points, then five units of change arrived at once, then nothing moved again. The number is roughly the right size and describes the wrong process entirely. Wrong tool for this shape of change, even when it doesn't look wrong.\n\n## Finding the Break by Hand\n\nHere's the idea, and it is about as simple as Mann-Kendall's pairwise sum. Try every possible split point. At each one, take the mean of everything before it and the mean of everything after, and add up how far every point sits from its own segment's mean. That leftover variation, the residual sum of squares, is small when the split falls right where the series actually changes and large everywhere else. The split that minimizes it is your best guess at the breakpoint.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrss_at_split <- function(x, k) {\n  before <- x[1:k]\n  after <- x[(k + 1):length(x)]\n  sum((before - mean(before))^2) + sum((after - mean(after))^2)\n}\n\ncandidates <- 5:(n - 5)\nrss <- map_dbl(candidates, rss_at_split, x = step)\nbest_split <- candidates[which.min(rss)]\nbest_split\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 44\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(split = candidates, rss = rss) |>\n  ggplot(aes(split, rss)) +\n  geom_line(color = sfPal[1]) +\n  geom_vline(xintercept = best_split, linetype = \"dashed\", color = sfPal[5]) +\n  labs(x = \"Candidate split point\", y = \"Leftover variation (RSS)\",\n       title = \"Where the series is best explained by two means instead of one\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09xAsideBreakpoints_files/figure-html/bp-byhand-plot-1.png){width=672}\n:::\n:::\n\n\nThe minimum lands at point 44, one point off the true break at 45, about as close as noisy data lets you get. Compare that RSS at the best split, 342.2, against the RSS if you'd insisted on a single mean for the whole series, 838.1. Cutting the series in two explains a lot more of it. That comparison, one mean's leftover variance against two means' leftover variance, is exactly what an F-test asks. This by-hand scan is a Chow test with extra steps.\n\n## A Formal Test: strucchange\n\n`strucchange::breakpoints()` runs the same search, more carefully. Instead of one split, it solves for the best partition at every number of breaks and lets BIC pick how many are actually worth keeping.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbp_step <- breakpoints(step ~ 1)\nbp_step$breakpoints\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 44\n```\n\n\n:::\n:::\n\n\nSame answer as the by-hand scan, point 44, because for one break they are the same calculation. What the package adds is a formal test for whether that break should be trusted at all, using the same F-statistic under the hood.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfs_step <- Fstats(step ~ 1)\nsctest(fs_step, type = \"supF\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tsupF test\n\ndata:  fs_step\nsup.F = 113.04, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\nAnd a confidence interval on the date itself, not just a point guess.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconfint(bp_step)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t Confidence intervals for breakpoints\n\t of optimal 2-segment partition: \n\nCall:\nconfint.breakpointsfull(object = bp_step)\n\nBreakpoints at observation number:\n  2.5 % breakpoints 97.5 %\n1    42          44     46\n\nCorresponding to breakdates:\n  2.5 % breakpoints 97.5 %\n1 0.525        0.55  0.575\n```\n\n\n:::\n:::\n\n\nFor the planted series that interval is tight, a couple of points either side of 44, because the jump is large and the noise is modest. Field data is rarely this cooperative, and the interval is where you'll feel that. The dynamic-programming search behind all of this, extending cleanly from one break to several, is @BaiPerron2003; the testing-and-dating framing used here, existence first, date second, follows @Zeileis2003.\n\n## Same Trap, Different Shape\n\nMann-Kendall's problem, from the last chapter, was autocorrelation: feed it a flat AR(1) series with no trend at all and it cries trend anyway, more often as $\\phi$ climbs. Does a break test fall into the same trap? Run the same kind of check, an AR(1) series with no break in it, and see how often `sctest` declares one anyway.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nar1_series <- function(phi, n) {\n  if (phi == 0) rnorm(n) else as.numeric(arima.sim(list(ar = phi), n = n))\n}\n\nbp_false_positive <- function(phi, n = 60, sims = 200) {\n  mean(replicate(sims, {\n    fs <- Fstats(ar1_series(phi, n) ~ 1)\n    sctest(fs, type = \"supF\")$p.value < 0.05\n  }))\n}\n\nset.seed(10)\nphis <- c(0, 0.3, 0.5, 0.7, 0.9)\nbp_fp <- tibble(phi = phis, rate = map_dbl(phis, bp_false_positive))\nbp_fp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 2\n    phi  rate\n  <dbl> <dbl>\n1   0   0.065\n2   0.3 0.255\n3   0.5 0.425\n4   0.7 0.765\n5   0.9 0.93 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(bp_fp, aes(factor(phi), rate)) +\n  geom_col(fill = sfPal[5], width = 0.6) +\n  geom_hline(yintercept = 0.05, linetype = \"dashed\") +\n  scale_y_continuous(labels = scales::percent) +\n  labs(x = expression(\"AR(1) coefficient \" * (phi)),\n       y = \"Breaks declared significant\",\n       title = \"A break test finds a break in break-free data too\",\n       subtitle = \"Share of 200 flat AR(1) series called significant at the 5% level\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09xAsideBreakpoints_files/figure-html/bp-mc-plot-1.png){width=672}\n:::\n:::\n\n\nSame trap, different shape of test. At $\\phi = 0$ the false-positive rate sits close to the nominal 5%. By $\\phi = 0.9$ it's declaring a break in most series that never had one. A run of correlated years looks, to an F-test built for independent noise, exactly like the kind of level shift it was built to catch. There is a fix, the same family of fix as GLS in the regression chapter: replace the test's covariance estimate with one that accounts for the autocorrelation instead of assuming it away [@Zeileis2003]. Building that correctly is more than this aside has room for, so take the caution as the headline: a breakpoint test run on a dependent series is just as capable of finding a break that isn't there as Mann-Kendall was of finding a trend that wasn't.\n\n## An Observed Series: the Nile, Again\n\nThe autocorrelation chapter introduced the Nile's annual flow at Aswan and pointed out a visible drop around the turn of the century, marked it as the Aswan Low Dam, under construction from 1898 and finished in 1902, and moved on, calling it a known break so it wouldn't distract from the autocorrelation question at hand. This is where we come back for it. Set the history aside for a moment: if all you had was the series, could you find that break on your own, and how sure could you be of the year?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(Nile)\nbp_nile <- breakpoints(Nile ~ 1)\nbp_nile$breakpoints\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 28\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnile_break_year <- time(Nile)[bp_nile$breakpoints]\nnile_ci <- confint(bp_nile)\nnile_ci_years <- time(Nile)[nile_ci$confint]\nnile_before <- mean(Nile[1:bp_nile$breakpoints])\nnile_after <- mean(Nile[(bp_nile$breakpoints + 1):length(Nile)])\n\nc(break_year = nile_break_year, before = round(nile_before, 1), after = round(nile_after, 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nbreak_year     before      after \n    1898.0     1097.8      850.0 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(year = as.numeric(time(Nile)), flow = as.numeric(Nile)) |>\n  ggplot(aes(year, flow)) +\n  geom_line(color = sfPal[1]) +\n  geom_vline(xintercept = nile_break_year, linetype = \"dashed\", color = sfPal[5]) +\n  annotate(\"rect\", xmin = nile_ci_years[1], xmax = nile_ci_years[2], ymin = -Inf, ymax = Inf,\n           fill = sfPal[5], alpha = 0.1) +\n  labs(x = \"Year\", y = expression(10^8~m^3),\n       title = \"River Nile, annual flow: best single break\",\n       subtitle = \"Shaded band is the 95% confidence interval on the break date\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](09xAsideBreakpoints_files/figure-html/bp-nile-plot-1.png){width=672}\n:::\n:::\n\n\nThe break lands at 1898, the year the dam's construction began, and the mean drops from 1097.8 to 850, about 247.8 (units of $10^8$ m$^3$) lower on average once the dam started holding water back. The 95% confidence interval, 1895 to 1898, brackets almost exactly the span from the start of construction to its completion. And the existence test isn't shy about it either.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfs_nile <- Fstats(Nile ~ 1)\nsctest(fs_nile, type = \"supF\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tsupF test\n\ndata:  fs_nile\nsup.F = 75.93, p-value = 2.22e-16\n```\n\n\n:::\n:::\n\n\nThat's what a break test looks like when the premise actually holds: one structural cause, one clean jump in the mean, and a date narrow enough to match the history books without having read them first. The planted step earlier in this aside was built to behave exactly this well. Most series aren't this obliging, which is worth remembering the next time a break test hands you a tight interval on something you can't independently check.\n\n## Where This Shows Up\n\nThe Nile had its answer waiting in the history books. Most series won't. A detected break is a hypothesis about a date, not an explanation, and before you trust one, go find out what actually happened around that year, a gauge relocation, a dam, a change in land use, a new instrument. Sometimes there's a clean answer. Sometimes there isn't, and the plain move is to say the series shifted and you don't know why. Either way, a breakpoint test and a trend test are asking different questions about the same word, \"change,\" and a series that fails one can still fail the other. Run both, and let the data tell you which shape it actually took.\n",
    "supporting": [
      "09xAsideBreakpoints_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}