{
  "hash": "43f6b027b9d2b9a72e8116225fbb9baa",
  "result": {
    "engine": "knitr",
    "markdown": "# Reconstruction\n\n\n::: {.cell}\n\n:::\n\n\n## Big Idea\n\nEvery chapter in this section of the book has fit a model and done something with it. We found the lag at which one series leads another, estimated a slope, tested a trend, and forecast a series forward. We know all models are wrong, right? But we've been asking is the model useful?  A model can fit the data it was built from beautifully and still be useless on anything else, because fitting and predicting are different acts. The only way to tell them apart is to hold some data back, build the model without it, and see whether the model can predict what it was never shown. That is out-of-sample validation.\n\nThis chapter makes that idea concrete by reconstructing the flow of the Colorado River back more than a thousand years from tree rings. We have a short instrumental record of flow and a long proxy that tracks it, we calibrate the relationship where the two overlap, we verify it on years the calibration never saw, and only then do we trust it to reach back before the gauges existed. The tree rings are the worked example. The transferable skill is the validation: the same split-sample check that tells a paleoclimatologist whether a reconstruction is sound is what tells you whether a load forecast or a calibration curve or any predictive model will hold up.\n\n## Packages\n\nWe hand-build the skill scores, fit the model with base R's `lm`, and use the `tidyverse` [@R-tidyverse] for wrangling and plotting. `slider` [@R-slider] gives us a clean centered running mean and `PNWColors` [@R-PNWColors] the palette. `forecast` [@R-forecast] gives us `ggAcf` to check the model's residuals, `nlme` [@R-nlme] gives us `gls` to confirm what that check shows, and `tseries` [@R-tseries] gives us `adf.test`/`kpss.test`, the same stationarity check from chapter four, to confirm the reconstruction itself.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(slider)\nlibrary(forecast)\nlibrary(nlme)\nlibrary(tseries)\nlibrary(PNWColors)\n\nbookPal <- pnw_palette(\"Sunset2\", n = 5, type = \"discrete\")\n```\n:::\n\n\n## A Short Record and a Long Proxy\n\nThe data are the Meko reconstruction of water-year flow for the Colorado River at Lees Ferry [@Meko2007]. Dave Meko built it with Connie Woodhouse, the same Woodhouse behind the precipitation-and-flow model we leaned on in the regression chapter [@Woodhouse2016]; the two of them have been reconstructing Colorado River flow together for decades, and @Woodhouse2006 is their fuller writeup of the calibration-and-verification method this chapter walks through. They are both legends in the paleo world. \n\nThere are two columns. `ObsMAF` is the observed flow in millions of acre-feet, which exists only for the instrumental period, 1906 to 2004.  Millions of acre-feet is on s list of worst units ever but it's what managers use. `Proxy` is a tree-ring index, expressed as a z-score, that runs all the way back to the year 762. Trees in the upper basin lay down wide rings in wet years and narrow ones in dry years, so the ring record is a stand-in for moisture that reaches back twelve centuries before anyone gauged the river. I get a little dreamy thinking about it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoRiverFlow <- read_csv(\"data/colorado_flow.csv\")\ninstrumental <- coRiverFlow |> filter(!is.na(ObsMAF))\n\ncor(instrumental$ObsMAF, instrumental$Proxy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8687286\n```\n\n\n:::\n:::\n\n\nThere are 1243 years of proxy and only 99 years of overlap with measured flow, and over that overlap the two move together with a correlation of 0.87. Always look at the data. Here is the long proxy on top and the short instrumental record below, on the same time axis, so you can see how little of the record we can actually check against a gauge.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npProxy <- ggplot(coRiverFlow, aes(Year, Proxy)) +\n  geom_line(color = bookPal[1], linewidth = 0.3) +\n  labs(y = \"Tree-ring index (z)\", x = NULL, title = \"The proxy reaches back to 762\") +\n  theme_minimal()\n\npFlow <- ggplot(coRiverFlow, aes(Year, ObsMAF)) +\n  geom_line(color = bookPal[5]) +\n  labs(y = \"Flow (MAF)\", x = \"Year\", title = \"The gauge starts in 1906\") +\n  theme_minimal()\n\ncowplot::plot_grid(pProxy, pFlow, ncol = 1, align = \"v\")\n```\n\n::: {.cell-output-display}\n![](11Reconstruction_files/figure-html/recon-data-plot-1.png){width=672}\n:::\n:::\n\n\nAnd here are the same data over the instrumental period.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npProxy <- ggplot(instrumental, aes(Year, Proxy)) +\n  geom_line(color = bookPal[1], linewidth = 0.3) +\n  geom_point(color = bookPal[1], alpha = 0.35) +\n  labs(y = \"Tree-ring index (z)\", x = NULL) +\n  theme_minimal()\n\npFlow <- ggplot(instrumental, aes(Year, ObsMAF)) +\n  geom_line(color = bookPal[5], linewidth = 0.3) +\n  geom_point(color = bookPal[5], alpha = 0.35) +\n  labs(y = \"Flow (MAF)\", x = \"Year\") +\n  theme_minimal()\n\npScatter <- ggplot(instrumental, aes(Proxy, ObsMAF)) +\n  geom_point(color = bookPal[3], alpha = 0.5) +\n  geom_smooth(method = \"lm\", se = FALSE, color = bookPal[3], linewidth = 0.7) +\n  labs(x = \"Tree-ring index (z)\", y = \"Flow (MAF)\") +\n  theme_minimal()\n\npSeries <- cowplot::plot_grid(pProxy, pFlow, ncol = 1, align = \"v\")\ncowplot::plot_grid(pSeries, pScatter, ncol = 2, rel_widths = c(1.3, 1))\n```\n\n::: {.cell-output-display}\n![](11Reconstruction_files/figure-html/recon-data-plot-zoom-1.png){width=672}\n:::\n:::\n\n\nThis is a stunning match between tree growth and river flow. And before we go any further let's look at the autocorrelation in these data over the instrumental record.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npProxyACF <- ggAcf(instrumental$Proxy) +\n  labs(title = \"Proxy data\") +\n  theme_minimal()\n\npFlowACF <- ggAcf(instrumental$ObsMAF) +\n  labs(title = \"Flow data\") +\n  theme_minimal()\n\ncowplot::plot_grid(pProxyACF,\n  pFlowACF,\n  ncol = 2, align = \"v\")\n```\n\n::: {.cell-output-display}\n![](11Reconstruction_files/figure-html/recon-proxy-acf-1.png){width=672}\n:::\n:::\n\n\nBoth show a significant AR(1) process. We'll have to keep that in mind as we continue to build a model.\n\nSo, if the rings track flow over the ninety-nine years where we can compare them, we can run the relationship backward and estimate flow for the twelve centuries where we cannot. The relationship is just a regression, `ObsMAF ~ Proxy`, the same tool from two chapters ago. \n\nOne thing worth being clear about before we fit anything. Writing `ObsMAF ~ Proxy` puts flow on the left and the tree rings on the right, and a regression like that often reads as effect on cause. Is that the claim, that tree growth causes the river to rise and fall? No. Both are downstream of the same cause, the winter snowpack and basin-wide moisture in a given year. A wide ring and a big flow year are two instruments recording the same weather, not one causing the other. The proxy sits on the right because it is the one thing we have for the centuries before any gauge existed, not because it drives the flow. That makes this a calibration, not a causal model. A strong $R^2$ here tells you the rings and the river are reading the same climate. It tells you nothing about which one, if either, is in charge.\n\n## Calibration and Verification\n\nThe tempting move is to fit the regression on all ninety-nine instrumental years and start reconstructing. Do not. A model graded on the same data that trained it will always look better than it is, because it has already seen the answers. The number that matters is how it does on data it has never met. So we split the instrumental record in two. We calibrate the model on one half and verify it on the other, predicting flow for years that took no part in the fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalib <- instrumental |> filter(Year <= 1955)\nverif <- instrumental |> filter(Year >= 1956)\n\nmodel <- lm(ObsMAF ~ Proxy, data = calib)\nverif <- verif |> mutate(pred = predict(model, verif))\n```\n:::\n\n\nBefore we score anything, look at the residuals, the same discipline the regression chapter insisted on. Both the proxy and the flow record carry their own year-to-year memory: a wet year tends to follow a wet year, and a wide ring tends to follow a wide ring, because soil moisture and stored carbohydrates both carry over. So you would be right to worry that the calibration model's errors carry that same memory, which would mean we have fewer independent years of evidence than the count of ninety-nine suggests.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggAcf(residuals(model)) +\n  labs(title = \"ACF of calibration-model residuals\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](11Reconstruction_files/figure-html/recon-resid-acf-1.png){width=672}\n:::\n:::\n\n\nUnlike the raw data, nothing crosses the band. These are the kind of numbers chance alone would produce. This is the ozone resolution from the regression chapter all over again: it is fine for the inputs to a regression to carry memory, what has to come out clean is what is left over once the line is fit. Here the proxy is doing the job temperature did for ozone. Both the rings and the river are responding to the same winter snowpack and spring runoff, so once the proxy is in the model there is no shared climate signal left for the residuals to inherit. A quick GLS fit confirms it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglsModel <- gls(ObsMAF ~ Proxy, data = calib, correlation = corAR1())\nsummary(glsModel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeneralized least squares fit by REML\n  Model: ObsMAF ~ Proxy \n  Data: calib \n       AIC      BIC    logLik\n  230.9269 238.4117 -111.4634\n\nCorrelation Structure: AR(1)\n Formula: ~1 \n Parameter estimate(s):\n       Phi \n0.07835457 \n\nCoefficients:\n                Value Std.Error  t-value p-value\n(Intercept) 14.820231 0.3595354 41.22051       0\nProxy        3.547026 0.3494127 10.15139       0\n\n Correlation: \n      (Intr)\nProxy -0.234\n\nStandardized residuals:\n        Min          Q1         Med          Q3         Max \n-2.61668075 -0.64302713 -0.02314921  0.77335588  2.38431950 \n\nResidual standard error: 2.288857 \nDegrees of freedom: 50 total; 48 residual\n```\n\n\n:::\n:::\n\n\nThe estimated AR(1) parameter comes back near zero, and the slope and its standard error barely move from the OLS fit. GLS has nothing to fix here, so we will not drag the rest of the chapter through it. Check, don't assume, and here the check says OLS already had it right. If you reconstruct something where that check fails, that is exactly when you would reach for `gls` the way the regression chapter did.\n\nNow we need a way to score the prediction. The natural question is whether the model does better than the dumbest defensible guess you could make, which is to ignore the proxy entirely and predict every year as the average flow. Two statistics from the paleoclimate literature put a number on exactly that, and both are simple enough to write by hand.\n\nThe reduction of error, RE, compares the model's squared errors against what you would get by guessing the *calibration* period mean for every verification year. The idea is to calibrate a proxy against a short instrumental record, then ask whether it earns its keep on years it never saw. Fritts and colleagues worked the statistic into standard dendroclimatology practice through the 1970s and 1980s, and it has been a fixture of reconstruction papers ever since [@CookKairiukstis1990]. The coefficient of efficiency, CE, does the same but against the *verification* period mean, which is a stiffer test because that mean is the best flat number you could have used for the years being predicted. CE did not grow up in dendrochronology at all: it is the Nash-Sutcliffe efficiency, imported wholesale from hydrology, where it has graded rainfall-runoff models since 1970 [@NashSutcliffe1970]. Different fields landed on the same arithmetic because they were asking the same question, how much better is the model than guessing a constant, on data the model never trained on.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskill <- function(obs, pred, calibMean) {\n  sse <- sum((obs - pred)^2)\n  RE <- 1 - sse / sum((obs - calibMean)^2)   # vs the calibration-period mean\n  CE <- 1 - sse / sum((obs - mean(obs))^2)     # vs the verification-period mean\n  c(RE = RE, CE = CE)\n}\n\nobsSkill <- skill(verif$ObsMAF, verif$pred, calibMean = mean(calib$ObsMAF))\nobsSkill\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       RE        CE \n0.8050336 0.7887489 \n```\n\n\n:::\n:::\n\n\nBoth come back well above zero. An RE or CE of zero means the model is no better than guessing the mean; anything above zero means it has skill on years it never saw, and one means perfect prediction. Getting a CE comfortably above zero is the result you want, because it is the harder of the two to clear. A model can post a high calibration $R^2$ and still fail here, and if it did, that would be the model telling you it had memorized the calibration period rather than learned anything that travels. This one travels.\n\nBut \"above zero\" is doing a lot of work in that sentence, so ask the obvious question: is zero actually a high bar? Neither RE nor CE has a textbook sampling distribution the way a correlation or an $R^2$ does. There is no `summary()` table with a p-value attached, because the statistic is not built from a model with known degrees of freedom, it is built from comparing two sums of squared errors with no assumed distribution behind either one. For most of the history of these statistics, the field's working answer was the threshold itself: above zero counts as skill.\n\nThat answer is not always safe. @MaciasFauria2012 showed that an autocorrelated proxy can clear zero by chance more often than the plain threshold assumes, for the same reason chapter eight warned about: persistence lets a relationship look stronger than it is, because the calibration and verification years are not as independent as their count suggests. The fix is the habit this book keeps coming back to. Don't trust the threshold. Build the null distribution yourself: simulate a proxy with no actual relationship to flow but the same year-to-year persistence as the one we have, run it through the identical calibration and verification, and see how often a meaningless proxy could produce an RE or CE this large.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nphiProxy <- acf(instrumental$Proxy, plot = FALSE)$acf[2]\nnCal <- nrow(calib)\nnVer <- nrow(verif)\nnTot <- nCal + nVer\n\nnSim <- 2000\nnullRE <- numeric(nSim)\nnullCE <- numeric(nSim)\nfor (i in 1:nSim) {\n  fakeProxy <- arima.sim(list(ar = phiProxy), n = nTot)\n  m <- lm(calib$ObsMAF ~ fakeProxy[1:nCal])\n  pred <- coef(m)[1] + coef(m)[2] * fakeProxy[(nCal + 1):nTot]\n  s <- skill(verif$ObsMAF, pred, calibMean = mean(calib$ObsMAF))\n  nullRE[i] <- s[\"RE\"]\n  nullCE[i] <- s[\"CE\"]\n}\n\nc(nullREMax = max(nullRE), nullCEMax = max(nullCE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nnullREMax nullCEMax \n0.1754816 0.1066130 \n```\n\n\n:::\n:::\n\n\n`phiProxy` is the lag-1 autocorrelation of the tree-ring index itself, about 0.27, so every simulated proxy carries the same persistence as the one we actually have without carrying any information about flow. Two thousand of them, and none come close. The best a meaningless, equally persistent proxy could manage was an RE of 0.18 and a CE of 0.11, nowhere near the 0.81 and 0.79 this proxy actually earned. So yes, these numbers are good, and now that conclusion comes from a Monte Carlo test. It is also worth noticing why the rule of thumb held up here: this proxy's persistence is mild. Run the same check on a more autocorrelated proxy and the safe threshold creeps up well past zero, which is exactly the point @MaciasFauria2012 make. Zero is not a law of nature, just a threshold that needs checking like anything else in this book.\n\nThere is nothing special about calibrating on the early half and verifying on the late half, so we should check it the other way too. Swapping the roles is standard practice, and a reconstruction you can trust should pass in both directions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvalidate <- function(cal, ver) {\n  m <- lm(ObsMAF ~ Proxy, data = cal)\n  pred <- predict(m, ver)\n  c(calibR2 = summary(m)$r.squared,\n    skill(ver$ObsMAF, pred, calibMean = mean(cal$ObsMAF)))\n}\n\nbind_rows(\n  `calibrate early, verify late` = validate(calib, verif),\n  `calibrate late, verify early` = validate(verif, calib),\n  .id = \"split\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  split                        calibR2    RE    CE\n  <chr>                          <dbl> <dbl> <dbl>\n1 calibrate early, verify late   0.689 0.805 0.789\n2 calibrate late, verify early   0.804 0.701 0.668\n```\n\n\n:::\n:::\n\n\nPositive RE and positive CE in both directions. This is the same move the forecasting chapter made when it withheld the tail of a series and predicted it, only now we are running it backward in time: holding out years, predicting them from the proxy, and checking. The model earns its trust on data it was not allowed to learn from, which is the only kind of trust worth having. Now, and only now, we reconstruct.\n\n## The Reconstruction\n\nWith the relationship validated, we refit it on the whole instrumental period to use every year of information we have, and apply it to the full twelve centuries of proxy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinalModel <- lm(ObsMAF ~ Proxy, data = instrumental)\ncoef(finalModel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)       Proxy \n  14.557266    3.533699 \n```\n\n\n:::\n\n```{.r .cell-code}\ncoRiverFlow <- coRiverFlow |>\n  mutate(recon = predict(finalModel, coRiverFlow),\n    reconSmooth = slide_dbl(recon, mean, .before = 12, .after = 12,\n      .complete = TRUE))\n```\n:::\n\n\nThe fitted relationship is ObsMAF $= 14.6 + 3.5 \\times \\text{proxy}$, in millions of acre-feet. Running it across the whole proxy gives an estimate of Colorado River flow for every year since 762. The annual reconstruction is noisy, so we overlay a 25-year centered running mean to bring out the slow swings, the droughts and pluvials that play out over decades.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(coRiverFlow, aes(Year)) +\n  geom_line(aes(y = recon), color = bookPal[1], linewidth = 0.2, alpha = 0.6) +\n  geom_line(aes(y = reconSmooth), color = bookPal[5], linewidth = 0.8) +\n  geom_hline(yintercept = mean(instrumental$ObsMAF), linetype = \"dashed\") +\n  labs(x = \"Year\", y = \"Reconstructed flow (MAF)\",\n    title = \"Colorado River flow at Lees Ferry, reconstructed from 762\",\n    subtitle = \"Thin line annual, thick line 25-year mean, dashed line the instrumental average\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](11Reconstruction_files/figure-html/recon-plot-1.png){width=672}\n:::\n:::\n\n\n## What the Long View Shows\n\nThe dashed line is the average flow over the instrumental period, the number everyone who manages the river grew up thinking of as normal. The reconstruction puts it in company, and the company is unflattering. Set the long record against that instrumental baseline.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstMean <- mean(instrumental$ObsMAF)\npctOfNormal <- function(years) {\n  round(100 * mean(coRiverFlow$recon[coRiverFlow$Year %in% years]) / instMean)\n}\n\nc(fullRecord = pctOfNormal(coRiverFlow$Year),\n  compactDecade1912_1921 = pctOfNormal(1912:1921),\n  megadrought1130_1154 = pctOfNormal(1130:1154),\n  dustBowl1933_1940 = pctOfNormal(1933:1940))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            fullRecord compactDecade1912_1921   megadrought1130_1154 \n                    97                    117                     83 \n     dustBowl1933_1940 \n                    91 \n```\n\n\n:::\n:::\n\n\nThe Colorado River Compact, which still governs how the river is divided among seven states and Mexico, was negotiated in 1922 using flow data from the preceding decade. That decade, 1912 to 1921, ran at 117% of the long-term average. The river was carved up on the basis of one of the wettest stretches in twelve hundred years, and the allocations have been writing checks the river cannot cash ever since. Meanwhile the full twelve-century record averages 97% of the instrumental mean, confirming that the gauged era itself ran a little wet. And the medieval megadrought of the twelfth century, 1130 to 1154, held the river at 83% of normal for a quarter century straight, a sustained drought deeper and longer than anything in the instrumental record, deeper than the Dust Bowl. None of that is visible from ninety-nine years of gauge data. You can only see it because the trees remembered, and you can only believe the trees because the reconstruction earned it in verification.\n\n## Stationarity Is Dead\n\n*Stationarity Is Dead: Whither Water Management?* is the title of an influential policy paper Milly and coauthors had in *Science* [@Milly2008]. Their argument: a warming climate has broken the assumption underneath a century of water engineering, that the statistics measured in the past, the means and variances engineers designed dams and allocations around, are a safe guide to the future. Once a climate is actively warming, that assumption stops holding, and water managers have to learn to plan without it.\n\nSo is the Colorado's reconstructed flow non-stationary, in the sense the paper means? Test it, the way chapter four tested Lake Huron.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadf.test(coRiverFlow$recon)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tAugmented Dickey-Fuller Test\n\ndata:  coRiverFlow$recon\nDickey-Fuller = -10.76, Lag order = 10, p-value = 0.01\nalternative hypothesis: stationary\n```\n\n\n:::\n\n```{.r .cell-code}\nkpss.test(coRiverFlow$recon)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKPSS Test for Level Stationarity\n\ndata:  coRiverFlow$recon\nKPSS Level = 0.041296, Truncation lag parameter = 7, p-value = 0.1\n```\n\n\n:::\n:::\n\n\nADF rejects the unit root, KPSS does not reject stationarity, and a line fit through all twelve hundred years comes back flat, even restricted to the centuries before any gauge existed. By every test in this book, the reconstruction is stationary, sensu stricto: no drift, no unit root, no trend across a thousand years.\n\nNone of that shrinks what comes next. Slide a 100-year window across the full twelve centuries and ask how often it would have landed wetter than the one the gauges actually recorded.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nroll100 <- slide_dbl(coRiverFlow$recon, mean, .before = 99, .complete = TRUE)\nroll100 <- roll100[!is.na(roll100)]\nround(100 * mean(roll100 > instMean), 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3.7\n```\n\n\n:::\n:::\n\n\nOnly 3.7% of the windows do. The instrumental record sits near the 96.3th percentile of everything the river has done since 762. A stationary process with this much natural variability can still hand you a deeply misleading 99-year sample, and that is what it did. Water law, reservoir design, and drought planning across the American West were built on that one stretch, mean and variance both, as if it were the river's settled character. Twelve centuries of tree rings say the stretch was generous, not settled.\n\nOnce you can see a thousand years of a river, you can see exactly how unrepresentative the slice anyone has ever gauged turns out to be.\n\nSo where does that leave Milly's actual claim? This record ends in 2004 and has nothing to say about the river since. What it does establish is that a river behaving exactly the way it always had was never the tame, well-behaved system anyone planning around the gauge record assumed. Whether the Colorado has since started to drift the way Milly's paper warns about is a separate question, and one this record cannot answer, because the proxy stops right where a warming signal would have to show up. @Woodhouse2016 picks up close to where this reconstruction leaves off and finds rising temperature already amplifying drought beyond what precipitation alone predicts, which is the kind of evidence that could eventually tip a river from stationary to not. Maybe stationarity was not dead in 2004, when this record ends. Maybe it is dying now.\n\nAnd notice what licenses any of this: the verification, not the tree rings on their own and not a confident-looking line through a scatterplot. The reason we can hold a record that sits at the 96th percentile of 100-year draws up against twelve centuries, or set the medieval megadrought next to the Dust Bowl, and take any of it seriously, is that the model behind it cleared an out-of-sample test, twice. Out-of-sample skill is the line between using the past to bound what is possible and merely fitting a curve and trusting your story.\n\n## Wrapping Up\n\nThe worked example was a streamflow reconstruction, but the chapter was about a habit. Before you trust a model to speak about data it has not seen, whether that is the deep past or next year's peak demand, you withhold, you predict, and you score the prediction against the plain baseline of guessing the mean. RE and CE are two ways to keep that score, and a model that clears them on held-out data has earned a kind of trust that calibration statistics alone can never grant. The forecasting chapter ran this validation forward into the future; here we ran it backward into the past, and it is the same discipline pointed in two directions. It is also the discipline that turns \"the software fit a model\" into \"I have a result I can stand behind,\" which is the whole project of this book.\n\n## Exercises\n\n### Move the wall\n\nWe split the instrumental record at 1955. Redo the validation with the split at 1930 and again at 1980, so that the calibration and verification periods are lopsided rather than even. Do RE and CE stay positive? Then try a harder test: calibrate on the middle of the record and verify on both ends at once. What does it tell you about a reconstruction if its skill depends a lot on where you put the wall, and what would you want to see before trusting it back to the year 762?\n\n### Find the pluvials\n\nThe chapter dwelt on droughts, but the reconstruction holds wet anomalies too. Using the 25-year running mean, find the wettest quarter-century in the whole record and compare it to the 1912 to 1921 decade that anchored the Compact. Was the decade the river was divided on merely wet, or close to the wettest the river has run in twelve hundred years? Write a sentence you would put in front of a water manager, with the number in it.\n\n## Further Reading\n\n- @Meko2007 is the reconstruction this chapter is built on, and it works through the medieval megadrought in the upper basin in detail.\n- @Woodhouse2006 lays out the streamflow reconstruction methods for the Colorado in full, including the calibration and verification practice we used here.\n- @CookKairiukstis1990 is the standard reference for RE and the rest of the dendroclimatology calibration-verification toolkit.\n- @NashSutcliffe1970 is where CE comes from, under its original name, decades before tree-ring scientists borrowed it.\n- @MaciasFauria2012 makes the case in detail that RE and CE need a Monte Carlo significance test, not a zero threshold, once a proxy carries meaningful persistence.\n",
    "supporting": [
      "11Reconstruction_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}