project:
  type: book
  output-dir: docs
  resources:
    - CNAME

book:
  title: "Time Series Analysis for Environmental Science"
  subtitle: "Course Notes"
  author: "Andy Bunn"
  date: today
  description: "Time series notes and exercises"
  navbar:
    background: dark
    search: true
  chapters:
    - file: index.qmd
      text: "Cover"
    - part: "Foundations"
      chapters:
        - 00Welcome.qmd
        - 01MeasureOfTime.qmd
        - 01xAsideMethods_and_generics.qmd
        - 01xAsideDatesAndTimes.qmd
        - 02DecompTrends.qmd
    - part: "The Anatomy of Dependence"
      chapters:
        - 03TimeSeries-Autocorrelation.qmd
        - 03xAsideCorrelationVersusRegression.qmd
        - 03xAsideMA1-ACF-PACF-Interp.qmd
        - 03xAsidePACFByHand.qmd
        - 04Stationarity.qmd
        - 05TimeSeries-ARMA.qmd
    - part: "Working with Dependence"
      chapters:
        - 06TimeSeries-Forecast.qmd
        - 07CrossCorrelation.qmd
        - 07xAsideCcfNormalization.qmd
        - 08TimeSeries-Regression.qmd
        - 08xAsideOLS-Algebra-Matrix.qmd
        - 09TrendDetection.qmd
        - 10Reconstruction.qmd
    - part: "The Frequency Domain"
      chapters:
        - 11TimeSeries-Filters.qmd
        - 12TimeSeries-Freq.qmd
    - 13PackagesUsed.qmd
  appendices:
    - A1DataSources.qmd
  repo-url: https://github.com/AndyBunn/timeSeriesBook
  repo-actions: [edit, issue]

bibliography:
  - packages.bib
  - dplR.bib
  - otherRefs.bib
reference-location: document
suppress-bibliography: true

format:
  html:
    theme: flatly
    css: style.css
    code-fold: show
    toc: true
    toc-depth: 4
    number-sections: false

execute:
  warning: false
  message: false
  freeze: auto