project:
  type: book
  output-dir: docs
  resources:
    - CNAME

book:
  title: "Time Series Analysis for Environmental Data"
  subtitle: "An R-Based Introduction"
  author: "Andy Bunn"
  date: today
  description: "Time series notes and exercises"
  navbar:
    background: dark
    search: true
  chapters:
    - file: index.qmd
      text: "Cover"
    - 00Preface.qmd
    - part: "Foundations"
      chapters:
        - 01Welcome.qmd
        - 02MeasureOfTime.qmd
        - 02xAsideDatesAndTimes.qmd
        - 02xAsideMethods_and_generics.qmd
        - 03DecompTrends.qmd
    - part: "The Anatomy of Dependence"
      chapters:
        - 04Autocorrelation.qmd
        - 04xAsideCorrelationVersusRegression.qmd
        - 04xAsideMA1-ACF-PACF-Interp.qmd
        - 04xAsidePACFByHand.qmd
        - 05Stationarity.qmd
        - 06ARMA.qmd
    - part: "Explore, Infer, Predict"
      chapters:
        - 07CrossCorrelation.qmd
        - 07xAsideCcfNormalization.qmd
        - 08Regression.qmd
        - 08xAsideOLS-Algebra-Matrix.qmd
        - 09TrendDetection.qmd
        - 10Forecast.qmd
        - 11Reconstruction.qmd
    - part: "The Frequency Domain"
      chapters:
        - 12Filters.qmd
        - 12xAsideMissingStations.qmd
        - 13Freq.qmd
        - 13xAsideCrossSpectrum.qmd
        - 14Wavelets.qmd
    - part: "Conclusion"
      chapters:
        - 15Conclusion.qmd
  appendices:
    - A1PackagesUsed.qmd
    - A2DataSources.qmd
  repo-url: https://github.com/AndyBunn/timeSeriesBook
  repo-actions: [edit, issue]

language:
  section-title-appendices: "Back Matter and Appendices"

bibliography:
  - packages.bib
  - dplR.bib
  - otherRefs.bib
reference-location: document
suppress-bibliography: true

format:
  html:
    theme: flatly
    css: style.css
    code-fold: show
    toc: true
    toc-depth: 4
    number-sections: false

execute:
  warning: false
  message: false
  freeze: auto