project:
  type: book
  output-dir: docs
  resources:
    - CNAME

book:
  title: "Time Series Analysis for Environmental Data"
  subtitle: "An R-Based Introduction"
  author: "Andy Bunn"
  date: today
  description: "Time series notes and exercises"
  navbar:
    background: dark
    search: true
  chapters:
    - file: index.qmd
      text: "Cover"
    - 00Preface.qmd
    - part: "Foundations"
      chapters:
        - 00Welcome.qmd
        - 01MeasureOfTime.qmd
        - 01xAsideMethods_and_generics.qmd
        - 01xAsideDatesAndTimes.qmd
        - 01xAsideMissingStations.qmd
        - 02DecompTrends.qmd
    - part: "The Anatomy of Dependence"
      chapters:
        - 03Autocorrelation.qmd
        - 03xAsideCorrelationVersusRegression.qmd
        - 03xAsideMA1-ACF-PACF-Interp.qmd
        - 03xAsidePACFByHand.qmd
        - 04Stationarity.qmd
        - 05ARMA.qmd
    - part: "Explore, Infer, Predict"
      chapters:
        - 06CrossCorrelation.qmd
        - 06xAsideCcfNormalization.qmd
        - 07Regression.qmd
        - 07xAsideOLS-Algebra-Matrix.qmd
        - 08TrendDetection.qmd
        - 09Forecast.qmd
        - 10Reconstruction.qmd
    - part: "The Frequency Domain"
      chapters:
        - 11Filters.qmd
        - 12Freq.qmd
        - 12xAsideCrossSpectrum.qmd
        - 13Wavelets.qmd
  appendices:
    - 14PackagesUsed.qmd
    - A1DataSources.qmd
  repo-url: https://github.com/AndyBunn/timeSeriesBook
  repo-actions: [edit, issue]

language:
  section-title-appendices: "Back Matter and Appendices"

bibliography:
  - packages.bib
  - dplR.bib
  - otherRefs.bib
reference-location: document
suppress-bibliography: true

format:
  html:
    theme: flatly
    css: style.css
    code-fold: show
    toc: true
    toc-depth: 4
    number-sections: false

execute:
  warning: false
  message: false
  freeze: auto