{
  "hash": "340cf01152bc99e8c5e2567e646059fc",
  "result": {
    "engine": "knitr",
    "markdown": "# Aside: Filling a Gap With a Neighbor {- .aside-chapter}\n\n\n::: {.cell}\n\n:::\n\n\n## Introduction\n\nEvery long-running weather station has a story about the years it wasn't running: a sensor failed, a funding line dried up, an airport moved its equipment and nobody thought to keep the old site going in parallel. The Bellingham airport station this book keeps coming back to (`kbli`) has one too. Its full 1949-to-present monthly record has a 27-month hole, July 1996 through September 1998, that shows up plainly as `NA` in `data/kbli_monthly.csv` rather than being papered over.\n\nA short gap in something that barely changes from one reading to the next (an hourly radiation sensor, say) can be patched by interpolating between its own neighbors, which is exactly what the filters chapter did with `na.approx()` and `na.spline()`. A 27-month hole in monthly temperature is a different problem: there is no straight line across two years that has any business standing in for two years of actual winters and summers. When the gap is that long, the fix people actually reach for in climate and weather work is not to look harder at the gappy station, it's to borrow information from a different station nearby that kept reporting the whole time.\n\n## Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(PNWColors)\n\nsfPal <- pnw_palette(\"Sunset2\", n = 5, type = \"discrete\")\n```\n:::\n\n\n## A Station Three Miles Away\n\n`USC00450587`, known in NOAA's records as Bellingham 3 SSW, sits about three miles south-southwest of the airport and is part of the Historical Climatology Network, one of NOAA's longer and more carefully maintained station sets. It was running the whole time the airport gauge went dark. `data/bellingham_3ssw_temp.csv` holds its monthly mean temperature, derived from daily TMAX/TMIN the same way `kbli`'s is.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkbli <- read_csv(\"data/kbli_monthly.csv\")\ndonor <- read_csv(\"data/bellingham_3ssw_temp.csv\") |> rename(donorTavg = TAVG)\n\nfull_join(kbli, donor, by = \"DATE\") |>\n  filter(DATE >= as.Date(\"1993-01-01\"), DATE <= as.Date(\"2001-12-01\")) |>\n  pivot_longer(c(TAVG, donorTavg), names_to = \"series\", values_to = \"tavg\") |>\n  mutate(series = recode(series,\n    TAVG = \"Bellingham Airport (kbli)\",\n    donorTavg = \"Bellingham 3 SSW (donor)\"\n  )) |>\n  ggplot(aes(DATE, tavg, color = series)) +\n  geom_line() +\n  scale_color_manual(values = c(\n    \"Bellingham Airport (kbli)\" = sfPal[1],\n    \"Bellingham 3 SSW (donor)\" = sfPal[5]\n  )) +\n  labs(\n    x = NULL, y = expression(degree * C), color = NULL,\n    title = \"The airport gap, and a station three miles away that kept reporting\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](12xAsideMissingStations_files/figure-html/gap-read-1.png){width=672}\n:::\n:::\n\n\nThe airport line simply stops in the middle of 1996 and doesn't pick back up until late 1998. The donor line runs straight through, tracking the same seasonal shape a little warmer year-round, which is what you'd expect from two nearby sites with slightly different exposure and elevation.\n\n## Calibrating the Donor\n\nBefore the donor station can stand in for the missing months, we need to know exactly how the two relate during the months they both reported.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverlap <- inner_join(kbli, donor, by = \"DATE\") |> drop_na()\nnrow(overlap)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 165\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(overlap, aes(donorTavg, TAVG)) +\n  geom_point(color = \"grey40\", alpha = 0.6) +\n  geom_smooth(method = \"lm\", se = FALSE, color = sfPal[5]) +\n  labs(\n    x = expression(\"Bellingham 3 SSW monthly \" * degree * C),\n    y = expression(\"Bellingham Airport monthly \" * degree * C),\n    title = paste(nrow(overlap), \"months where both stations reported\")\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](12xAsideMissingStations_files/figure-html/gap-overlap-1.png){width=672}\n:::\n:::\n\n\n165 months, and the relationship is close to a straight line the whole way from winter lows to summer highs. A simple linear model captures it well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noverlapFit <- lm(TAVG ~ donorTavg, data = overlap)\nsummary(overlapFit)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.984201\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef(overlapFit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)   donorTavg \n  -1.303921    1.033950 \n```\n\n\n:::\n:::\n\n\nAn R² of 0.984 and a slope close to 1 (1.03) with a small negative intercept (-1.3): the airport runs a little cooler than the inland donor site, consistently, across the full range of temperatures either station sees.\n\n## Does It Actually Work?\n\nA good fit on the months you already have doesn't automatically mean the donor will do a good job standing in for months you don't have. Test it the way this book always tests a model before trusting it: hold out a stretch of known months, refit on everything else, predict the held-out stretch from the donor alone, and check the damage.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrainSet <- overlap |> filter(year(DATE) < 2000 | year(DATE) > 2003)\ntestSet <- overlap |> filter(year(DATE) >= 2000, year(DATE) <= 2003)\n\nvalidateFit <- lm(TAVG ~ donorTavg, data = trainSet)\ntestPred <- predict(validateFit, newdata = testSet)\nrmseRegression <- sqrt(mean((testPred - testSet$TAVG)^2))\n\nclimLookup <- trainSet |>\n  mutate(mo = month(DATE)) |>\n  group_by(mo) |>\n  summarise(climMean = mean(TAVG))\nrmseClimatology <- testSet |>\n  mutate(mo = month(DATE)) |>\n  left_join(climLookup, by = \"mo\") |>\n  summarise(rmse = sqrt(mean((climMean - TAVG)^2))) |>\n  pull(rmse)\n\ntibble(\n  method = c(\"donor regression\", \"climatology baseline\"),\n  rmseDegC = c(rmseRegression, rmseClimatology)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 2\n  method               rmseDegC\n  <chr>                   <dbl>\n1 donor regression        0.441\n2 climatology baseline    1.35 \n```\n\n\n:::\n:::\n\n\nThe withheld stretch is 2000 through 2003, four years nowhere near the actual gap, chosen only because the true values are known and can be checked against. The donor-based regression misses by about 0.44°C on average; a naive baseline that just uses each calendar month's long-run average misses by about 1.35°C, roughly 3.1 times worse. The donor station is picking up the specific weather in a specific month, not just the season, and that's exactly the property you want before you let it speak for two years you can't check.\n\n## Filling the Gap\n\nWith the technique validated, refit on every month of overlap (more data than the validation split used) and predict the 27 months the airport actually missed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinalFit <- lm(TAVG ~ donorTavg, data = overlap)\n\ngapFilled <- kbli |>\n  filter(is.na(TAVG)) |>\n  select(DATE) |>\n  inner_join(donor, by = \"DATE\") |>\n  mutate(\n    TAVG = predict(finalFit, newdata = tibble(donorTavg = donorTavg)),\n    source = \"filled\"\n  )\n\nkbliComplete <- kbli |>\n  drop_na() |>\n  mutate(source = \"measured\") |>\n  bind_rows(gapFilled) |>\n  arrange(DATE)\n\nkbliComplete |>\n  filter(DATE >= as.Date(\"1993-01-01\"), DATE <= as.Date(\"2001-12-01\")) |>\n  ggplot(aes(DATE, TAVG, color = source)) +\n  geom_line(aes(group = 1), color = \"grey70\") +\n  geom_point(size = 1) +\n  scale_color_manual(values = c(measured = \"grey30\", filled = sfPal[5])) +\n  labs(\n    x = NULL, y = expression(degree * C), color = NULL,\n    title = \"27 months filled from the donor\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](12xAsideMissingStations_files/figure-html/gap-fill-1.png){width=672}\n:::\n:::\n\n\n`kbliComplete` is a new object built just for this aside. It is not a replacement for `data/kbli_monthly.csv`, and the filters chapter's version of this record still shows the gap exactly as measured. The point here isn't that every gap should be filled by default; it's that when you decide to fill one, the `source` column above is not decorative: three years from now, whoever reuses this series should be able to tell instantly which 27 points are estimates riding on a neighboring station's word, not readings off Bellingham's own instrument.\n\n## Closing\n\nThis aside used one hand-picked neighbor and a plain linear regression, because that's enough to show the idea working end to end on an actual 27-month hole. National weather services do a more careful version of the same thing at scale (multiple neighboring stations, formal checks for undocumented station moves and instrument changes, statistical tests for whether the target and donor drift apart over time), all built on the same foundation: find a series that correlates with the one you're missing, calibrate the relationship on the months you can check, and validate that calibration on more months you can check before you ever apply it to months you can't.\n\nOne thing worth being direct about: this aside only fills temperature. The daily record behind `kbli` also carries a `PRCP` column, and a climatologist trying to reconstruct a complete station history would need to close that gap too. Precipitation doesn't cooperate the way temperature does. Rain and snow fall in patches, a storm can soak one station and miss another three miles away, so two nearby gauges correlate far less tightly than two nearby thermometers do. Precip is also zero-inflated, most months have several days that report exactly zero, which breaks the assumptions behind a plain linear regression like `overlapFit`. Filling a precipitation gap properly usually calls for something like a generalized linear model built around that zero-inflation, not the two-line `lm()` this aside got away with for temperature.\n",
    "supporting": [
      "12xAsideMissingStations_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}