{
  "hash": "631fa0564d13cf57bef27da8ee3e9106",
  "result": {
    "engine": "knitr",
    "markdown": "# Reconstruction\n\n\n::: {.cell}\n\n:::\n\n\n## Big Idea\n\nEvery chapter in this part has fit a model and read something off it. We forecast a series forward, found the lag at which one series leads another, estimated a slope and tested a trend. Underneath all of it sits one question we have circled but never met head on: how do you know the model is not lying to you? A model can fit the data it was built from beautifully and still be worthless on anything else, because fitting and predicting are different acts. The only way to tell them apart is to hold some data back, build the model without it, and see whether the model can predict what it was never shown. That is out-of-sample validation, and it is the hardest test you can put a model to.\n\nThis chapter makes that idea concrete by reconstructing the flow of the Colorado River back more than a thousand years from tree rings. We have a short instrumental record of flow and a long proxy that tracks it, we calibrate the relationship where the two overlap, we verify it on years the calibration never saw, and only then do we trust it to reach back before the gauges existed. The tree rings are the worked example, but the transferable skill is the validation. The same split-sample check that tells a paleoclimatologist whether a reconstruction is sound is what tells you whether a load forecast or a calibration curve or any predictive model will hold up. It is also where the book's spine finally pays off in full: once you can see a thousand years of a river, you can see how small and how unrepresentative the slice we call \"normal\" actually is.\n\n## Packages\n\nWe hand-build the skill scores, fit the model with base R's `lm`, and use the tidyverse for wrangling and plotting. `slider` gives us a clean centered running mean and `PNWColors` the palette.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(slider)\nlibrary(PNWColors)\n\nsfPal <- pnw_palette(\"Starfish\", n = 5, type = \"discrete\")\n```\n:::\n\n\n## A Short Record and a Long Proxy\n\nThe data are the Meko reconstruction of water-year flow for the Colorado River at Lees Ferry [@Meko2007]. There are two measured columns. `ObsMAF` is the observed flow in millions of acre-feet, which exists only for the instrumental period, 1906 to 2004. `Proxy` is a tree-ring index, expressed as a z-score, that runs all the way back to the year 762. Trees in the upper basin lay down wide rings in wet years and narrow ones in dry years, so the ring record is a stand-in for moisture that reaches back twelve centuries before anyone gauged the river.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nflow <- read_csv(\"data/colorado_flow.csv\")\ninstrumental <- flow |> filter(!is.na(ObsMAF))\n\nc(proxy_years = nrow(flow),\n  instrumental_years = nrow(instrumental),\n  overlap_cor = cor(instrumental$ObsMAF, instrumental$Proxy))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       proxy_years instrumental_years        overlap_cor \n      1243.0000000         99.0000000          0.8687286 \n```\n\n\n:::\n:::\n\n\nThere are 1243 years of proxy and only 99 years of overlap with measured flow, and over that overlap the two move together with a correlation of 0.87. Always look at the data. Here is the long proxy on top and the short instrumental record below, on the same time axis, so you can see how little of the record we can actually check against a gauge.\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_proxy <- ggplot(flow, aes(Year, Proxy)) +\n  geom_line(color = sfPal[1], linewidth = 0.3) +\n  labs(y = \"Tree-ring index (z)\", x = NULL, title = \"The proxy reaches back to 762\") +\n  theme_minimal()\n\np_flow <- ggplot(instrumental, aes(Year, ObsMAF)) +\n  geom_line(color = sfPal[5]) +\n  labs(y = \"Flow (MAF)\", x = \"Year\", title = \"The gauge starts in 1906\") +\n  coord_cartesian(xlim = range(flow$Year)) +\n  theme_minimal()\n\ncowplot::plot_grid(p_proxy, p_flow, ncol = 1, align = \"v\")\n```\n\n::: {.cell-output-display}\n![](10Reconstruction_files/figure-html/recon-data-plot-1.png){width=672}\n:::\n:::\n\n\nThe plan writes itself. If the rings track flow over the ninety-nine years where we can compare them, we can run the relationship backward and estimate flow for the twelve centuries where we cannot. The relationship is just a regression, `ObsMAF ~ Proxy`, the same tool from two chapters ago. The hard part is not fitting it. The hard part is earning the right to believe it out where there is nothing to check it against.\n\n## Calibration and Verification\n\nThe tempting move is to fit the regression on all ninety-nine instrumental years and start reconstructing. Do not. A model graded on the same data that trained it will always look better than it is, because it has already seen the answers. The number that matters is how it does on data it has never met. So we split the instrumental record in two. We calibrate the model on one half and verify it on the other, predicting flow for years that took no part in the fit.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalib <- instrumental |> filter(Year <= 1955)\nverif <- instrumental |> filter(Year >= 1956)\n\nmodel <- lm(ObsMAF ~ Proxy, data = calib)\nverif <- verif |> mutate(pred = predict(model, verif))\n```\n:::\n\n\nNow we need a way to score the prediction. The natural question is whether the model does better than the dumbest defensible guess you could make, which is to ignore the proxy entirely and predict every year as the average flow. Two statistics from the reconstruction literature put a number on exactly that, and both are simple enough to write by hand. The reduction of error, RE, compares the model's squared errors against what you would get by guessing the *calibration* period mean for every verification year. The coefficient of efficiency, CE, does the same but against the *verification* period mean, which is a stiffer test because that mean is the best flat number you could have used for the years being predicted.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskill <- function(obs, pred, calib_mean) {\n  sse <- sum((obs - pred)^2)\n  RE <- 1 - sse / sum((obs - calib_mean)^2)   # vs the calibration-period mean\n  CE <- 1 - sse / sum((obs - mean(obs))^2)     # vs the verification-period mean\n  c(RE = RE, CE = CE)\n}\n\nskill(verif$ObsMAF, verif$pred, calib_mean = mean(calib$ObsMAF))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       RE        CE \n0.8050336 0.7887489 \n```\n\n\n:::\n:::\n\n\nBoth come back well above zero. An RE or CE of zero means the model is no better than guessing the mean; anything above zero means it has skill on years it never saw, and one means perfect prediction. Getting a CE comfortably above zero is the result you want, because it is the harder of the two to clear. A model can post a high calibration $R^2$ and still fail here, and if it did, that would be the model telling you it had memorized the calibration period rather than learned anything that travels. This one travels.\n\nThere is nothing special about calibrating on the early half and verifying on the late half, so we should check it the other way too. Swapping the roles is standard practice, and a reconstruction you can trust should pass in both directions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvalidate <- function(cal, ver) {\n  m <- lm(ObsMAF ~ Proxy, data = cal)\n  pred <- predict(m, ver)\n  c(calib_R2 = summary(m)$r.squared,\n    skill(ver$ObsMAF, pred, calib_mean = mean(cal$ObsMAF)))\n}\n\nbind_rows(\n  `calibrate early, verify late` = validate(calib, verif),\n  `calibrate late, verify early` = validate(verif, calib),\n  .id = \"split\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 4\n  split                        calib_R2    RE    CE\n  <chr>                           <dbl> <dbl> <dbl>\n1 calibrate early, verify late    0.689 0.805 0.789\n2 calibrate late, verify early    0.804 0.701 0.668\n```\n\n\n:::\n:::\n\n\nPositive RE and positive CE in both directions. This is the same move the forecasting chapter made when it withheld the tail of a series and predicted it, only now we are running it backward in time: holding out years, predicting them from the proxy, and checking. The model earns its trust on data it was not allowed to learn from, which is the only kind of trust worth having. Now, and only now, we reconstruct.\n\n## The Reconstruction\n\nWith the relationship validated, we refit it on the whole instrumental period to use every year of information we have, and apply it to the full twelve centuries of proxy.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfinal_model <- lm(ObsMAF ~ Proxy, data = instrumental)\ncoef(final_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept)       Proxy \n  14.557266    3.533699 \n```\n\n\n:::\n\n```{.r .cell-code}\nflow <- flow |>\n  mutate(recon = predict(final_model, flow),\n         recon_smooth = slide_dbl(recon, mean, .before = 12, .after = 12,\n                                  .complete = TRUE))\n```\n:::\n\n\nThe fitted relationship is flow $= 14.6 + 3.5 \\times \\text{proxy}$, in millions of acre-feet. Running it across the whole proxy gives an estimate of Colorado River flow for every year since 762. The annual reconstruction is noisy, so we overlay a 25-year centered running mean to bring out the slow swings, the droughts and pluvials that play out over decades.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(flow, aes(Year)) +\n  geom_line(aes(y = recon), color = sfPal[1], linewidth = 0.2, alpha = 0.6) +\n  geom_line(aes(y = recon_smooth), color = sfPal[5], linewidth = 0.8) +\n  geom_hline(yintercept = mean(instrumental$ObsMAF), linetype = \"dashed\") +\n  labs(x = \"Year\", y = \"Reconstructed flow (MAF)\",\n       title = \"Colorado River flow at Lees Ferry, reconstructed from 762\",\n       subtitle = \"Thin line annual, thick line 25-year mean, dashed line the instrumental average\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](10Reconstruction_files/figure-html/recon-plot-1.png){width=672}\n:::\n:::\n\n\n## What the Long View Shows\n\nThe dashed line is the average flow over the instrumental period, the number everyone who manages the river grew up thinking of as normal. The reconstruction puts it in company, and the company is unflattering. Set the long record against that instrumental baseline.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninst_mean <- mean(instrumental$ObsMAF)\npct_of_normal <- function(years) {\n  round(100 * mean(flow$recon[flow$Year %in% years]) / inst_mean)\n}\n\nc(full_record = pct_of_normal(flow$Year),\n  compact_decade_1912_1921 = pct_of_normal(1912:1921),\n  megadrought_1130_1154 = pct_of_normal(1130:1154),\n  dust_bowl_1933_1940 = pct_of_normal(1933:1940))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             full_record compact_decade_1912_1921    megadrought_1130_1154 \n                      97                      117                       83 \n     dust_bowl_1933_1940 \n                      91 \n```\n\n\n:::\n:::\n\n\nTwo of those numbers should stop you. The Colorado River Compact, which still governs how the river is divided among seven states and Mexico, was negotiated in 1922 using flow data from the preceding decade. That decade, 1912 to 1921, ran at 117% of the long-term average. The river was carved up on the basis of one of the wettest stretches in twelve hundred years, and the allocations have been writing checks the river cannot cash ever since. Meanwhile the full twelve-century record averages 97% of the instrumental mean, confirming that the gauged era itself ran a little wet. And the medieval megadrought of the twelfth century, 1130 to 1154, held the river at 83% of normal for a quarter century straight, a sustained drought deeper and longer than anything in the instrumental record, deeper than the Dust Bowl. None of that is visible from ninety-nine years of gauge data. You can only see it because the trees remembered, and you can only believe the trees because the reconstruction earned it in verification.\n\n## Stationarity Is Dead\n\nThis is where the spine of the book comes to rest. From the start we have treated stationarity as an assumption you have to earn rather than one you can help yourself to, and a river is the place that lesson bites hardest. Water law, reservoir design, and drought planning across the American West were all built on the premise that the future will look statistically like the instrumental past, that the mean and the variance we measured in the twentieth century are the river's settled character. The reconstruction says otherwise. The twentieth century was a short, wet, unrepresentative sample, and the river has spent long stretches of the Common Era in drought regimes the gauges never captured [@Milly2008]. Planning on a stationary Colorado is planning on a fiction.\n\nAnd notice what licenses that claim. It is not the tree rings on their own, and it is not a confident-looking line through a scatterplot. It is the verification. The reason we can hold the megadrought up next to the instrumental record and take it seriously is that the model predicting it cleared an out-of-sample test, twice. Out-of-sample skill is the line between using the past to bound what is possible and merely fitting a curve and believing your own story. Earn it, and a thousand years of river is yours to reason with. Skip it, and you have a number the software was happy to print.\n\n## Wrapping Up\n\nThe worked example was a streamflow reconstruction, but the chapter was about a habit. Before you trust a model to speak about data it has not seen, whether that is the deep past or next year's peak demand, you withhold, you predict, and you score the prediction against the plain baseline of guessing the mean. RE and CE are two ways to keep that score, and a model that clears them on held-out data has earned a kind of trust that calibration statistics alone can never grant. The forecasting chapter ran this validation forward into the future; here we ran it backward into the past, and it is the same discipline pointed in two directions. It is also the discipline that turns \"the software fit a model\" into \"I have a result I can stand behind,\" which is the whole project of this book.\n\n## Exercises\n\n### Move the wall\n\nWe split the instrumental record at 1955. Redo the validation with the split at 1930 and again at 1980, so that the calibration and verification periods are lopsided rather than even. Do RE and CE stay positive? Then try a harder test: calibrate on the middle of the record and verify on both ends at once. What does it tell you about a reconstruction if its skill depends a lot on where you put the wall, and what would you want to see before trusting it back to the year 762?\n\n### Find the pluvials\n\nThe chapter dwelt on droughts, but the reconstruction holds wet anomalies too. Using the 25-year running mean, find the wettest quarter-century in the whole record and compare it to the 1912 to 1921 decade that anchored the Compact. Was the decade the river was divided on merely wet, or close to the wettest the river has run in twelve hundred years? Write a sentence you would put in front of a water manager, with the number in it.\n\n## Further Reading\n\n- @Meko2007 is the reconstruction this chapter is built on, and it works through the medieval megadrought in the upper basin in detail.\n- @Woodhouse2006 lays out the streamflow reconstruction methods for the Colorado in full, including the calibration and verification practice we used here.\n- @Milly2008 is the \"Stationarity Is Dead\" paper, the clearest statement of why a validated look at the deep past matters for managing water under a changing climate.\n",
    "supporting": [
      "10Reconstruction_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}